config/routes.rb
Rails.application.routes.draw do

  get 'tweets/new'

  get 'tweets/create'

  devise_for :users
  root to: "sites#index"

  resources :sites
  resources :jobs
  resources :tweets, only: [:new, :create]

  match "/likes/create", to: "likes#create", via: "post"
  match "/sites/create", to: "sites#create", via: "post"
  match "/developers", to: "static_pages#developers", via: "get"
  match "/dashboard", to: "static_pages#user_dashboard", via: "get"
  match "/user/jobs", to: "static_pages#user_jobs_dashboard", via: "get"
  match "/user/sites", to: "static_pages#user_sites_dashboard", via: "get"
  match "/admin/dashboard", to: "static_pages#admin_dashboard", via: "get"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  before_filter :authenticate_user!, only: :developers 

  def developers
  end

  def user_dashboard
  end

  def user_jobs_dashboard
  end

  def user_sites_dashboard
  end

  def admin_dashboard
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin_dashboard.html.erb
<% @page_title = "Admin Dashboard" %>
<h1>Hi Mate</h1>
<div class="boxes dashboard admin_dashboard">

	<div class="box sites">
		<h2>Last 5 Users. Total <%= @users.size %> </h2>
		<table>
			<tr>
				<th width="30%">Name Surname</th>
				<th width="20%">Role</th>
				<th width="20%" class="right">Created</th>
				<th width="30%" class="right">Actions</th>
			</tr>
			<% @users.last(5).each do |user| %>
			<tr>
				<td><%= user.name %> <%= user.surname %></td>
				<td><%= user.role.name %></td>
				<td class="right"><%= user.created_at.strftime("%h' %d") %></td>
				<td class="right">
					<%= link_to "Edit", edit_user_registration_path(id: user.id) %>
					<%= link_to "Delete", user_registration_path(id: user.id), method: :delete, data: {confirm: "Are you sure you want to delete '#{user.name}'" } %>
				</td>
			</tr>
			<% end %>
		</table>
	</div>

	<div class="box sites">
		<h2>Last 5 Sites. Total <%= @sites.size %> </h2>
		<table>
			<tr>
				<th width="30%">Name</th>
				<th width="20%">Author</th>
				<th width="20%" class="right">Created</th>
				<th width="30%" class="right">Actions</th>
			</tr>
			<% @sites.last(5).each do |site| %>
			<tr>
				<td><%= site.title %></td>
				<td><%= site.user.name %> <%= site.user.surname %></td>
				<td class="right"><%= site.created_at.strftime("%h' %d") %></td>
				<td class="right">
					<%= link_to "Edit", edit_site_path(id: site.id) %>
					<%= link_to "Delete", site_path(id: site.id), method: :delete, data: {confirm: "Are you sure you want to delete '#{site.title}'" } %>
				</td>
			</tr>
			<% end %>
		</table>
		<%= link_to "Submit a website", new_site_path, class: "btn red" %>
	</div>

	<div class="box jobs">
		<h2>Last 5 Jobs. Total <%= @jobs.size %></h2>
		<table>
			<tr>
				<th width="30%">Title</th>
				<th width="20%">Author</th>
				<th width="20%" class="right">Created</th>
				<th width="30%" class="right">Actions</th>
			</tr>
			<% @jobs.last(5).each do |job| %>
			<tr>
				<td><%= job.title %></td>
				<td><%= job.user.name %> <%= job.user.surname %></td>
				<td class="right"><%= job.created_at.strftime("%h' %d") %></td>
				<td class="right">
					<%= link_to "Edit", edit_site_path(id: job.id) %>
					<%= link_to "Delete", site_path(id: job.id), method: :delete, data: {confirm: "Are you sure you want to delete '#{job.title}'" } %>
				</td>
			</tr>
			<% end %>
		</table>
		<%= link_to "Post a job", new_job_path, class: "btn red" %>
	</div>

</div>

app/views/static_pages/developers.html.erb
<% @page_title = "Ruby, Ruby on Rails, Sinatra Developers" %>
<% @page_description = "Find and hire Ruby, Ruby on Rails, Sinatra professionals from around the globe." %>
<h1>Developers</h1>
<div class="developers">
	<ul class="dev_list">
		<% @developers.each do |dev| %>
			<li id="<%= dev.name.downcase + dev.surname.downcase + dev.id.to_s %>">
				<div class="image">
					<%= image_tag dev.avatar %>
					<div class="names"><!--<%= dev.name %>--></div>
				</div>
				<div class="extra_info">
					<h3><%= dev.name %> <%= dev.surname %></h3>
					<div class="role"><%= dev.roletitle %></div>
					<div class="bio"><p><%= dev.biography %></p></div>
					<div class="social_media">
						<% if dev.facebook.blank? == false %>
							<a href="https://facebook.com/<%= dev.facebook %>" class="linkedin"><i class="fa fa-facebook"></i></a>
						<% end %>
						<% if dev.twitter.blank? == false %>
							<a href="https://twitter.com/<%= dev.twitter %>" class="twitter"><i class="fa fa-twitter"></i></a>
						<% end %>
						<% if dev.github.blank? == false %>
							<a href="https://github.com/<%= dev.github %>" class="github"><i class="fa fa-github"></i></a>
						<% end %>
						<% if dev.linkedin.blank? == false %>
							<a href="<%= dev.linkedin %>" class="linkedin"><i class="fa fa-linkedin"></i></a>
						<% end %>
					</div>
					<% if dev.sites.size > 0 %>
						<div class="sites"><p><%= dev.sites.size %> sites posted</p></div>
					<% end %>
				</div>
			</li>
		<% end %>
	<ul>
</ul>

app/views/static_pages/user_dashboard.html.erb
<% @page_title = "My Dashboard" %>
<h1>My Dashboard</h1>
<div class="boxes dashboard">

	<div class="box profile">
		<div class="info">
			<div class="avatar"><%= image_tag(current_user.avatar) %></div>
			<div class="right">
				<h3 class="name"><%= current_user.name %> <%= current_user.surname %></h3>
				<div class="role"><%= current_user.roletitle %></div>
				<div class="bio"><%= current_user.biography %></div>
				<%= link_to "Edit profile", edit_user_registration_path, class: "btn red" %>
			</div>
		</div>
	</div>

	<div class="box sites">
		<h2>My Sites</h2>
		<table>
			<tr>
				<th width="50%">Name</th>
				<th width="20%" class="right">Created at</th>
				<th width="30%" class="right">Actions</th>
			</tr>
			<% @sites_from_user.each do |site| %>
			<tr>
				<td><%= site.title %></td>
				<td class="right"><%= site.created_at.strftime("%h' %d") %></td>
				<td class="right">
					<%= link_to "Edit", edit_site_path(id: site.id) %>
					<%= link_to "Delete", site_path(id: site.id), method: :delete, data: {confirm: "Are you sure you want to delete '#{site.title}'" } %>
				</td>
			</tr>
			<% end %>
		</table>
		<%= link_to "Submit a website", new_site_path, class: "btn red" %>
	</div>

	<div class="box jobs">
		<h2>My Jobs</h2>
		<table>
			<tr>
				<th width="50%">Title</th>
				<th width="20%" class="right">Created at</th>
				<th width="30%" class="right">Actions</th>
			</tr>
			<% @jobs_from_user.each do |job| %>
			<tr>
				<td><%= job.title %></td>
				<td class="right"><%= job.created_at.strftime("%h' %d") %></td>
				<td class="right">
					<%= link_to "Edit", edit_site_path(id: job.id) %>
					<%= link_to "Delete", site_path(id: job.id), method: :delete, data: {confirm: "Are you sure you want to delete '#{job.title}'" } %>
				</td>
			</tr>
			<% end %>
		</table>
		<%= link_to "Post a job", new_job_path, class: "btn red" %>
	</div>

</div>

app/views/static_pages/user_jobs_dashboard.html.erb
<% @page_title = "Jobs Dashboard" %>
<h1>Your Jobs</h1>
<div class="centralized user_jobs">
	<table>
		<% if @jobs_from_user.size > 0 %>
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th>Created</th>
				<th></th>
			</tr>
			<% @jobs_from_user.each do |job| %>
				
				<tr>
					<td><%= link_to job.title, edit_job_path(id: job.id) %></td>
					<td><%= strip_tags(job.description).truncate(130) %></td>
					<% if ((job.created_at + 1.month) - Time.now).to_i == 0 %>
						<td><span>Expired</span></td>
					<% end %>
					<td><%= job.created_at.strftime("%h' %d") %></td>
					<td>
						<%= link_to "Edit", edit_job_path(id: job.id) %>
						<%= link_to "Delete", job_path(id: job.id), method: :delete, data: {confirm: "Are you sure you want to delete '#{job.title}'" } %>
					</td>
				</tr>
			<% end %>
		<% else %>
			<tr>
				<td>You haven't posted any jobs yet.</td>
			</tr>
		<% end %>
	</table>
	<br>
	<%= link_to "Post a job", new_job_path, class: "btn red" %>
</div>

app/views/static_pages/user_sites_dashboard.html.erb
<% @page_title = "Sites Dashboard" %>
<h1>Your Sites</h1>
<div class="centralized user_jobs">
	<table>
		<% if @sites_from_user.size > 0 %>
			<tr>
				<th>Name</th>
				<th>Description</th>
				<th>Created</th>
				<th></th>
			</tr>
			<% @sites_from_user.each do |site| %>
				<tr>
					<td><%= link_to site.title, edit_site_path(id: site.id) %></td>
					<td><%= strip_tags(site.description).truncate(130) %></td>
					<td><%= site.created_at.strftime("%h' %d") %></td>
					<td>
						<%= link_to "Edit", edit_site_path(id: site.id) %>
						<%= link_to "Delete", site_path(id: site.id), method: :delete, data: {confirm: "Are you sure you want to delete '#{site.title}'" } %>
					</td>
				</tr>
			<% end %>
		<% else %>
			<tr>
				<td>You haven't posted any sites yet.</td>
			</tr>
		<% end %>
	</table>
	<br>
	<%= link_to "Post a site", new_site_path, class: "btn red" %>
</div>