config/routes.rb
Rails.application.routes.draw do

  get 'tweets/new'

  get 'tweets/create'

  devise_for :users
  root to: "sites#index"

  resources :sites
  resources :jobs
  resources :tweets, only: [:new, :create]

  match "/likes/create", to: "likes#create", via: "post"
  match "/sites/create", to: "sites#create", via: "post"
  match "/developers", to: "static_pages#developers", via: "get"
  match "/dashboard", to: "static_pages#user_dashboard", via: "get"
  match "/user/jobs", to: "static_pages#user_jobs_dashboard", via: "get"
  match "/user/sites", to: "static_pages#user_sites_dashboard", via: "get"
  match "/admin/dashboard", to: "static_pages#admin_dashboard", via: "get"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :subscribe
  before_create :set_default_role

  has_many :sites
  has_many :jobs
  has_many :likes
  belongs_to :role

  #Subscribe User to Mailchimp
  after_create :subscribe_to_list 

  #User avatar
  has_attached_file :avatar, styles: { medium: "600x600>", thumb: "100x100>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  def set_default_role
  	self.role ||= Role.find_by_name('registered')
  end

  def subscribe_to_list
    #If the subcribe box is checked, subscribe the User
    if self.subscribe == "1"
      @list_id = Rails.application.secrets.mailchimp_list_id
      gb = Gibbon::Request.new(api_key: Rails.application.secrets.mailchimp_api_key)

      gb.lists(@list_id).members.create(body: {
        email_address: self.email, 
        status: "subscribed", 
        merge_fields: {
          FNAME: self.name, 
          LNAME: self.surname
        }
      })
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/shared/_userprofile.html.erb
<div class="profile_cont">
	<div class="profile_info">
		<div class="avatar"><%= image_tag current_user.avatar %></div>
		<div class="left">
			<h2><%= current_user.name %> <%= current_user.surname %></h2>
			<div class="role"><%= current_user.roletitle %></div>
			<div class="clear"></div>
			<div class="bio"><%= current_user.biography %></div>
			<%= link_to "Edit Profile", edit_user_registration_path(id: current_user.id), class: "btn white" %>
		</div>
	</div>
	<%= link_to "Logout", destroy_user_session_path, class: "logout", method: :delete %>
</div>
<div class="profile_stats">
	<% if @sites_from_user.size > 0 %>
		<h3>Your website submissions</h3>
		<table>
			<% @sites_from_user.each do |site| %>
				<tr>
					<td><strong><%= site.title %></strong></td>
					<td><%= site.description.truncate(65) %></td>
					<td><%= site.created_at.strftime("%h' %d") %></td>
				</tr>
			<% end %>
		</table>
	<% end %>
	<% if @jobs_from_user.size > 0 %>
		<br/><br/>
		<h3>Your job submissions</h3>
		<table>
			<% @jobs_from_user.each do |job| %>
				<tr>
					<td width="70%"><strong><%= job.title %></strong></td>
					<td width="10%" style="text-align: center;"><%= job.created_at.strftime("%h' %d") %></td>
					<td width="10%" style="text-align: right;"><%= link_to "Edit", edit_job_path(id: job.id) %></td>
					<td width="10%" style="text-align: right;"><%= link_to "Delete", job_path(id: job.id), method: :delete, data: {confirm: "Are you sure you want to delete '#{job.title}'" } %></td>
				</tr>
			<% end %>
		</table>
	<% end %>
</div>