config/routes.rb
Rails.application.routes.draw do

  get 'tweets/new'

  get 'tweets/create'

  devise_for :users
  root to: "sites#index"

  resources :sites
  resources :jobs
  resources :tweets, only: [:new, :create]

  match "/likes/create", to: "likes#create", via: "post"
  match "/sites/create", to: "sites#create", via: "post"
  match "/developers", to: "static_pages#developers", via: "get"
  match "/dashboard", to: "static_pages#user_dashboard", via: "get"
  match "/user/jobs", to: "static_pages#user_jobs_dashboard", via: "get"
  match "/user/sites", to: "static_pages#user_sites_dashboard", via: "get"
  match "/admin/dashboard", to: "static_pages#admin_dashboard", via: "get"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta charset="UTF-8" />
  <meta name="Description" content="<%= @page_description %>" />
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">

  <!--<link href='https://fonts.googleapis.com/css?family=Hind+Siliguri:400,700,500,300' rel='stylesheet' type='text/css'>-->
  <link href='https://fonts.googleapis.com/css?family=Noto+Sans:400,400italic,700,700italic' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
</head>
<body>
<% if flash.empty? == false %>
	<div class="notice"><%= flash[:notice] %></div>
<% end %>

<header id="mainHeader">
	<!--<div class="account">
	<% if user_signed_in? %>
		<div class="panel">
			<%= render partial: "users/shared/userprofile" %>
		</div>
		<span class="name resource">Hi, <%= current_user.name %> <%= current_user.surname %></span>
	<% else %>
		<div class="panel login">
			<h2>Login</h2>
			<%= form_for(:user, url: session_path(:user)) do |f| %>
			  <div class="top">
				  <div class="field">
				    <%= f.email_field :email, placeholder: "Email", autofocus: true %>
				  </div>
				  <div class="field">
				    <%= f.password_field :password, placeholder: "Password", autocomplete: "off" %>
				  </div>
				  <div class="actions">
				    <%= f.submit "Log in", class: "btn white" %>
				    <span>or</span>
				    <%= link_to "Sign up", new_user_registration_path, class: "btn green" %>
				  </div>
			  </div>
			  <div class="field remember">
			    <%= f.check_box :remember_me %>
			    <%= f.label :remember_me %>
			  </div>
			<% end %>
		</div>
		<span class="resource">Login</span>
	<% end %>
	<div class="clear"></div>
	</div>-->
	<div class="centralized">
		<%= link_to(image_tag("logo.jpg"), root_path, id: "logo") %>
		<nav id="mainNav">
			<ul>
				<% if request.original_url.include?("sites") %>
					<li class="current"><%= link_to "Submit a site", new_site_path %></li>
				<% else %>
					<li><%= link_to "Submit a site", new_site_path %></li>
				<% end %>
				<% if request.original_url.include?("jobs") %>
					<li class="current"><%= link_to "Jobs (#{@jobs.size})", jobs_path %></li>
				<% else %>
					<li><%= link_to "Jobs (#{@jobs.size})", jobs_path %></li>
				<% end %>
				<!--<% if request.original_url.include?("developers") %>
					<li class="current"><%= link_to "Developers (#{@developers.size})", developers_path %></li>
				<% else %>
					<li><%= link_to "Developers (#{@developers.size})", developers_path %></li>
				<% end %>-->
			</ul>
		</nav>
		<% if user_signed_in? and current_user.role_id != 4 %>
			<div class="current_user">
				<div class="avatar"><%= image_tag(current_user.avatar) %></div>
				<span class="name">Hi, <%= current_user.name %></span>
				<ul>
					<li><%= link_to "Your Jobs", user_jobs_path %></li>
					<li><%= link_to "Your Sites", user_sites_path %></li>
					<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				</ul>
			</div>
		<% elsif user_signed_in? and current_user.role_id = 4 %>
			<div class="current_user">
				<div class="avatar"><%= image_tag(current_user.avatar) %></div>
				<span class="name">Hi, <%= current_user.name %></span>
				<ul>
					<li><%= link_to "Dashboard", admin_dashboard_path %></li>
					<li><%= link_to "Jobs", user_jobs_path %></li>
					<li><%= link_to "Sites", user_sites_path %></li>
					<li><%= link_to "Edit Profile", edit_user_registration_path %></li>
					<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
				</ul>
			</div>
		<% else %>
		<div class="panel_login">
			<%= link_to "Login", new_user_session_path, class: "account_btn" %>
			<span>or</span>
			<%= link_to "Register", new_user_registration_path, class: "create_account" %>
		</div>
		<% end %>
	</div>
</header>
<div class="clear"></div>

<%= yield %>

<footer id="mainFooter">
<p>This website was proudly done on Ruby on Rails, while traveling on the Trans-Siberian railway from Moscow to Vladivostok (9,173 km ~ 5700 miles). By <a href="http://thenordicland.io" target="_blank">thenordicland.io</a> and <a href="http://expand-business.co.uk" target="_blank">Expand-Business</a></p>
<div class="right">
	<a href="https://twitter.com/builtonruby_" class="twitter">Twitter</a>
	<a href="https://www.facebook.com/builtonruby" class="twitter">Facebook</a>
	<!--<a href="" class="twitter">LinkedIn</a>-->
</div>
</footer>

<!-- Tracking Code -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-23824283-6', 'auto');
  ga('send', 'pageview');

</script>

</body>
</html>